apiVersion: v1
kind: ConfigMap
metadata:
  name: monolithapp-config
  namespace: monolithapp
data:
  SPRING_APPLICATION_NAME: monolithapp
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/monolithapp
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
  SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_H2_CONSOLE_ENABLED: "false"
